#!/usr/bin/env bash
# to be used just on master branch

function tag
{
    echo $RELEASE_TAG_REF
    git tag $RELEASE_TAG_REF
    #git push --tags
}

function release
{
    if [ -z "$1" ]
    then
        mkdir -p ci/rendered
        pip install semver
        ci/bootstrap/bin/subst < ci/templates/old-release > ci/rendered/old-release
        export $(xargs <ci/rendered/old-release)
        ci/bootstrap/bin/subst < ci/templates/new-release > ci/rendered/new-release
        export $(xargs <ci/rendered/new-release)
    else
        export RELEASE_TAG_REF=$1
    fi
    tag
}

release $@
