version: '3'

services:
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    volumes:
    - grafana_data:/var/lib/grafana
    - ./prometheus/graphana_dashboards_provisioner.yaml:/etc/grafana/provisioning/dashboards/graphana_dashboards_provisioner.yaml
    - ./prometheus/graphana_dashboards.json:/etc/grafana/provisioning/dashboards/graphana_dashboards.json
    - ./prometheus/graphana_datasource.yaml:/etc/grafana/provisioning/datasources/graphana_datasource.yaml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus_data:/prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml

  idunn:
    ports:
    - 5000:5000
    environment:
     - IDUNN_MIMIR_ES=

volumes:
  prometheus_data:
  grafana_data:
