{
 "title": "Idunn",
 "time": { "from": "2018-10-08T06:04:29.962Z", "to": "2018-10-08T10:04:29.962Z" },
 "panels": [
  { "title": "main metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "total /pois/ queries",
   "type": "graph",
   "description": "total queries done in idunn",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler=\"idunn.api.pois.get_poi\"}[1m])) by (code)",
     "legendFormat": "{{handler}}-{{code}}"
    }
   ]
  },
  {
   "title": "request per 1m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=\"idunn\", handler!=\"apistar_prometheus.handlers.expose_metrics_multiprocess\"}[1m])) by (code, handler)",
     "legendFormat": "{{handler}} - {{code}}"
    }
   ]
  },
  {
   "title": "request per week",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{handler=\"idunn.api.pois.get_poi\"}[7d]))"
    }
   ]
  },
  {
   "title": "request in progress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_inprogress{handler!~\"<builtin>\"}) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "request per day",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{handler=\"idunn.api.pois.get_poi\"}[1d]))"
    }
   ]
  },
  {
   "title": "request per hour",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{handler=\"idunn.api.pois.get_poi\"}[1h]))"
    }
   ]
  },
  { "title": "/pois duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "mean duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_seconds_sum{handler=\"idunn.api.pois.get_poi\"}[1m])/rate(http_request_duration_seconds_count{handler=\"idunn.api.pois.get_poi\"}[1m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percentile duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{handler=\"idunn.api.pois.get_poi\"}[1m])) by (le))",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{handler=\"idunn.api.pois.get_poi\"}[1m])) by (le))",
     "legendFormat": "90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{handler=\"idunn.api.pois.get_poi\"}[1m])) by (le))",
     "legendFormat": "99"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(idunn_exceptions_count[1m])) by (exception_type)",
     "legendFormat": "{{exception_type}}"
    }
   ]
  },
  { "title": "wiki calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "number of calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(idunn_wiki_request_duration_seconds_count[1m])) by (handler, target)",
     "legendFormat": "{{target}} - {{handler}}"
    }
   ]
  },
  {
   "title": "wikipedia mean duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "avg(rate(idunn_wiki_request_duration_seconds_sum[1m])/rate(idunn_wiki_request_duration_seconds_count[1m])) by (handler, target)",
     "legendFormat": "{{target}} - {{handler}}"
    }
   ]
  },
  {
   "title": "wikipedia percentile duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(idunn_wiki_request_duration_seconds_bucket[1m])) by (le, target, handler))",
     "legendFormat": "50 - {{target}} - {{handler}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(idunn_wiki_request_duration_seconds_bucket[1m])) by (le, target, handler))",
     "legendFormat": "90 - {{target}} - {{handler}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(idunn_wiki_request_duration_seconds_bucket[1m])) by (le, target, handler))",
     "legendFormat": "99 - {{target}} - {{handler}}"
    }
   ]
  }
 ]
}