on: [push, pull_request]

env:
  DOCKER_IMAGE_BASENAME: qwantresearch/idunn

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        if: github.event_name != 'pull_request'
        run: |
          REF=${GITHUB_REF#refs/*/}
          if [ "$REF" == "master" ]; then
            IMAGE_TAG=latest
          else
            # Replace '/' with '__'
            IMAGE_TAG=${REF//\//__}
          fi
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      - name: Extract branch name
        if: github.event_name == 'pull_request'
        run: |
          echo "IMAGE_TAG=$GITHUB_HEAD_REF" >> $GITHUB_ENV

      # extract branch name on pull request
      - name: Print branch name
        run: echo "${IMAGE_TAG}"

      - name: Set env variables
        run: |
          echo "DOCKER_IMAGE=${DOCKER_IMAGE_BASENAME}:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get image name
        run: |
          VERSION=${GITHUB_REF#refs/*/}
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            IMAGE_TAG=$GITHUB_SHA
          elif [ "$VERSION" == "master" ]; then
            IMAGE_TAG=latest
          elif [ "$VERSION" == "es7" ]; then
            IMAGE_TAG=latest-es7
          else
            IMAGE_TAG=$VERSION
          fi
          echo "DOCKER_IMAGE=$DOCKER_IMAGE_BASENAME:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
          tags: ${{ env.DOCKER_IMAGE }}
          labels: org.label-schema.vcs-ref=${{ github.sha }}
          cache-from: type=registry,branch=${{ github.branch }}
          cache-to: type=inline
